import { notFound } from 'next/navigation'
import { createClient } from '@supabase/supabase-js'
import { createClient as createServerClient } from '@/lib/supabase/server'
import type { Metadata } from 'next'
import WalkReportCard from './WalkReportCard'

type WalkReport = {
  id: string
  token: string
  customer_id: string | null
  dog_name: string
  walk_date: string
  duration_mins: number
  poop_count: number
  pee_count: number
  notes: string | null
  photo_url: string | null
  provider_name: string
  is_verified: boolean
  verification_tier: string
  start_location: string | null
  end_location: string | null
  route_points: {lat: number, lng: number}[] | null
  distance_meters: number | null
  poop_events: {lat: number, lng: number, time: string}[] | null
  pee_events: {lat: number, lng: number, time: string}[] | null
}

async function getReport(token: string): Promise<WalkReport | null> {
  const admin = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  )

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (admin.from('walk_reports') as any)
    .select('*, providers(name, is_verified, verification_tier)')
    .eq('token', token)
    .single()

  if (error || !data) return null

  return {
    id: data.id,
    token: data.token,
    customer_id: data.customer_id ?? null,
    dog_name: data.dog_name,
    walk_date: data.walk_date,
    duration_mins: data.duration_mins,
    poop_count: data.poop_count,
    pee_count: data.pee_count,
    notes: data.notes ?? null,
    photo_url: data.photo_url ?? null,
    provider_name: data.providers?.name ?? 'Your Walker',
    is_verified: data.providers?.is_verified ?? false,
    verification_tier: data.providers?.verification_tier ?? 'contacted',
    start_location: data.start_location ?? null,
    end_location: data.end_location ?? null,
    route_points: data.route_points ?? null,
    distance_meters: data.distance_meters ?? null,
    poop_events: data.poop_events ?? null,
    pee_events: data.pee_events ?? null,
  }
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ token: string }>
}): Promise<Metadata> {
  const { token } = await params
  const report = await getReport(token)

  if (!report) return { title: 'Walk Report · PawLocal' }

  const dogName = report.dog_name
  const walkerName = report.provider_name ?? 'Your dog walker'
  const duration = report.duration_mins ? `${report.duration_mins} mins` : ''
  const poop = report.poop_count > 0 ? `💩 ${report.poop_count}` : ''
  const pee = report.pee_count > 0 ? `💧 ${report.pee_count}` : ''
  const stats = [poop, pee, duration].filter(Boolean).join(' · ')
  const distance = report.distance_meters && report.distance_meters > 0
    ? report.distance_meters >= 1000
      ? `${(report.distance_meters / 1000).toFixed(1)} km`
      : `${Math.round(report.distance_meters)} m`
    : null

  // WhatsApp / iMessage preview: emoji-rich, warm, parent-friendly
  const title = `🐾 ${dogName}'s Walk Report`
  const description = [
    `${dogName} just had a great walk with ${walkerName} in Juhu, Mumbai!`,
    stats && `Stats: ${stats}`,
    distance && `📏 ${distance} covered`,
  ].filter(Boolean).join(' ')

  // Use configured site URL, fall back to Vercel's automatic URL, then the known Vercel deployment
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL
    ?? (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'https://pawlocal-ashen.vercel.app')
  const canonicalUrl = `${baseUrl}/walk-report/${token}`

  return {
    title,
    description,
    // OG image is auto-generated by opengraph-image.tsx in this route folder
    openGraph: {
      title,
      description,
      url: canonicalUrl,
      siteName: 'PawLocal',
      type: 'article',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
    },
  }
}

export default async function WalkReportPage({
  params,
}: {
  params: Promise<{ token: string }>
}) {
  const { token } = await params
  const report = await getReport(token)

  if (!report) notFound()

  const supabase = await createServerClient()
  const { data: { user } } = await supabase.auth.getUser()

  const isClaimed = report.customer_id !== null
  const isClaimedByMe = report.customer_id !== null && report.customer_id === user?.id

  return <WalkReportCard report={report} isClaimed={isClaimed} isClaimedByMe={isClaimedByMe} />
}
